# Generated by Django 4.2.2 on 2024-10-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Введите страну проживания",
                max_length=150,
                null=True,
                verbose_name="Страна",
            ),
        ),
    ]
