# Generated by Django 5.0.6 on 2024-09-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="название")),
                ("body", models.TextField(verbose_name="содержимое")),
            ],
            options={
                "verbose_name": "Пост в блоге",
                "verbose_name_plural": "Посты в блоге",
            },
        ),
    ]
