# Generated by Django 4.2.2 on 2024-10-09 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_category_options_alter_product_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.CharField(max_length=50, verbose_name="Номер версии"),
                ),
                (
                    "version_name",
                    models.CharField(max_length=150, verbose_name="Название версии"),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False, verbose_name="Признак текущей версия"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="catalog.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия продукта",
                "verbose_name_plural": "Версии продукта",
                "ordering": ["product"],
            },
        ),
    ]
