# Generated by Django 4.2.2 on 2024-10-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("name",),
                "permissions": [
                    ("can_unpublish_product", "Can unpublish product"),
                    (
                        "can_change_product_description",
                        "Can change product description",
                    ),
                    ("can_change_product_category", "Can change product category"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Опубликован"),
        ),
    ]
